print("This file was created within Sumi's RStudio")
print("And now it lives on Sumitra Binu's GitHub EDATest repository")
k<-read.csv("mtcars.csv")
load(datasets)
data()
View(mtcars)
summary(mtcars)
names(mtcars)
